services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    expose:
     - "3306"
  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    expose:
      - 9000
  rest-mvc:
    container_name: rest-mvc
    image: spring-backend-rest-mysql:0.0.1-SNAPSHOT
    expose:
      - 8080
    environment:
      - SPRING_PROFILES_ACTIVE=localmysql
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/restdb    
      - SERVER_PORT=8080
    depends_on:
      mysql:
        condition: service_healthy
  gateway:
    container_name: gateway
    image: spring-6-gateway:0.0.1-SNAPSHOT
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://auth-server:9000
    depends_on:
      - auth-server
      - rest-mvc






































